export const initialState = {
  connected: false,
  connectionState: "connecting",
  lastTelemetryAt: 0,
  identity: {
    username: "user",
    hostname: "host",
    os: "Windows",
    uptimeSeconds: null,
  },
  telemetry: {
    timestamp: 0,
    cpu: null,
    gpu: null,
    memory: null,
    storage: null,
    network: null,
  },
  weather: {
    available: false,
    temperatureC: null,
    condition: "acquiring",
    updatedAt: 0,
  },
  media: {
    enabled: true,
    state: "stopped",
    title: "",
    artist: "",
    album: "",
    thumbnail: "",
    primaryColor: "",
    position: null,
    duration: null,
    trackKey: "",
    sessionId: "",
    sourceAppId: "",
    mediaType: "unknown",
    capturedAt: 0,
    playbackRate: 1,
  },
  settings: {
    accentRgb: [112, 190, 255],
    uiScale: 1,
    brightness: 0.9,
    animationIntensity: 0.6,
    glowStrength: 0.35,
    scanlines: 0.02,
    bootSequence: true,
    showMedia: true,
    showWeather: true,
    showStorage: true,
    showClock: true,
    clock24Hour: true,
    temperatureUnit: "c",
    networkUnit: "auto",
    telemetryRate: 1000,
    fps: 30,
  },
};
