<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>false</InvariantGlobalization>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <AssemblyName>QuietSystem.Telemetry</AssemblyName>
    <RootNamespace>QuietSystem.Telemetry</RootNamespace>
    <DefaultItemExcludes>$(DefaultItemExcludes);publish\**;.packages\**;.dotnet-home\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
    <PackageReference Include="NAudio" Version="2.4.0" />
  </ItemGroup>
</Project>
