<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../telemetry/Networking/PseudoConsoleProcess.cs" Link="PseudoConsoleProcess.cs" />
    <Compile Include="../../telemetry/Networking/CommandSocketSession.cs" Link="CommandSocketSession.cs" />
  </ItemGroup>
</Project>
